// Generates the drop's sixteen moods as a static asset for the browser extension, from the web
// app's own source (apps/web/lib/drop.ts), so the browser and the web app never drift.
//   bun scripts/generate-drop-assets.ts
// Run with the repo root as the working directory. `extension/build/` is gitignored (matches the
// repo's generic `build` rule) — the extension's e2e harness regenerates it before every run.
import { DROP_PATH, FACE_MARKUP } from "../apps/web/lib/drop.ts"

const OUT = "extension/build/moods.generated.js"

export function renderMoodsJs(): string {
  const data = JSON.stringify({ path: DROP_PATH, faces: FACE_MARKUP }, null, 2)
  return `// Generated by scripts/generate-drop-assets.ts from apps/web/lib/drop.ts — do not edit by hand.\nself.ZEN_DROP = ${data}\n`
}

if (import.meta.main) {
  await Bun.write(OUT, renderMoodsJs())
  console.log(`wrote drop assets (${Object.keys(FACE_MARKUP).length} moods) to ${OUT}`)
}
